import {bag,saveBag,currentProduct,checkoutUrl,esc,money} from './commerce.js';
const list=document.getElementById('bag-items'),status=document.getElementById('bag-status'),checkout=document.getElementById('checkout');
function render(){const items=bag();list.innerHTML=items.map(p=>`<li class="bag-row"><a href="product.html?p=${encodeURIComponent(p.handle)}">${p.image?`<img src="${esc(p.image)}" alt="" width="100" height="125">`:''}</a><div><a href="product.html?p=${encodeURIComponent(p.handle)}">${esc(p.title)}</a><p>${esc(p.variant)}</p><p>${money(p.price)} each</p><label for="qty-${p.id}">Quantity</label><input id="qty-${p.id}" data-id="${p.id}" type="number" min="1" max="20" step="1" value="${p.quantity}"><button type="button" class="text-link" data-remove="${p.id}" aria-label="Remove ${esc(p.title)}">Remove</button></div><strong>${money(p.price*p.quantity)}</strong></li>`).join('');
 document.getElementById('bag-empty').hidden=!!items.length;checkout.disabled=!items.length;document.getElementById('bag-total').textContent=money(items.reduce((n,p)=>n+p.price*p.quantity,0));
 list.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{saveBag(bag().filter(p=>p.id!==b.dataset.remove));render();status.textContent='Item removed from your bag.';}));
 list.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{const q=Number(input.value);if(!Number.isInteger(q)||q<1||q>20)return;const items=bag().map(p=>p.id===input.dataset.id?{...p,quantity:q}:p);saveBag(items);const item=items.find(p=>p.id===input.dataset.id);if(item)input.closest('.bag-row').querySelector('strong').textContent=money(item.price*q);document.getElementById('bag-total').textContent=money(items.reduce((n,p)=>n+p.price*p.quantity,0));}));
}
checkout.addEventListener('click',async()=>{const invalid=list.querySelector('input:invalid');if(invalid){invalid.reportValidity();return;}checkout.disabled=true;status.textContent='Checking your items with the store…';try{const items=bag(),updated=[];let priceChanged=false;for(const item of items){const product=await currentProduct(item.handle);const v=product.variants.find(v=>v.id===item.id);if(!v?.available)throw new Error(`${item.title}: this option is no longer available. Remove it or choose another option.`);priceChanged ||= v.price!==item.price;updated.push({...item,price:v.price});}saveBag(updated);if(priceChanged){render();status.textContent='The store updated a price. Review the new subtotal, then continue to checkout.';return;}location.assign(checkoutUrl(updated));}catch(e){status.textContent=e.message;checkout.disabled=false;}});
window.addEventListener('storage',render);render();
