import {readFile,writeFile,rename} from 'node:fs/promises';
import {catalog,card,esc} from '../catalog-core.js';
const previous=JSON.parse(await readFile('products.json','utf8'));
const data=await catalog(previous);
if(new Set(data.products.map(p=>p.handle)).size!==data.products.length||data.products.some(p=>!p.variants.length||!Number.isFinite(p.price)))throw new Error('Catalog validation failed; existing files preserved');
const outputs={'products.json':JSON.stringify(data.products),'products-data.js':`window.MBFC_CATALOG=${JSON.stringify(data)};window.MBFC_PRODUCTS=window.MBFC_CATALOG.products;\n`};
let shop=await readFile('shop.html','utf8');
shop=shop.replace(/(<ul class="product-grid shop-grid" id="grid">)[\s\S]*?<\/ul>/,(_,start)=>`${start}\n${data.products.map(card).join('\n')}\n</ul>`).replace(/(<span id="count">)\d+/,(_,start)=>start+data.products.length);
outputs['shop.html']=shop;
outputs['shop.html']=shop.replace(/(<select id="collection">)[\s\S]*?<\/select>/,(_,start)=>start+'<option value="">All collections</option>'+data.collections.map(c=>`<option value="${esc(c.handle)}">${esc(c.title)}</option>`).join('')+'</select>');
let home=await readFile('index.html','utf8');
home=home.replace(/(<ul class="product-grid"(?: id="home-products")?>)[\s\S]*?<\/ul>/,(_,start)=>`${start}\n${data.products.filter(p=>p.available).slice(0,4).map(card).join('\n')}\n</ul>`);
outputs['index.html']=home;
const root='https://my-best-friends-closet.jabach0811.chatgpt.site/';
outputs['sitemap.xml']=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['','shop.html','consign.html','brands.html','jewelry.html','hats.html','contact.html','policies.html',...data.products.map(p=>'product.html?p='+encodeURIComponent(p.handle))].map(p=>`<url><loc>${esc(root+p)}</loc></url>`).join('')}</urlset>`;
for(const [file,content] of Object.entries(outputs))await writeFile(file+'.tmp',content);
for(const file of Object.keys(outputs))await rename(file+'.tmp',file);
console.log(`Synchronized ${data.products.length} products, ${data.collections.length} collections, ${data.products.reduce((n,p)=>n+p.variants.length,0)} variants. ${data.updatedAt}`);
